### ISSUE TITLE
Brilliant work / fix

### ISSUE THREAD

**Issue by lonkelle** [SoY0ung/SideStore#1]
Hey, I'm Joelle, I started the SideStore project and I was wondering if you maybe wanted to join our GitHub organization and / or our private SideStore-Devs-only Discord?

If so, join the Discord and ping me and I'll give you the appropriate team member roles: https://discord.gg/kMkxdRRs

**Comment by SoY0ung** [comment]
Hi Joelle,
Thank you for the invitation to join the SideStore team. While I am honored to be considered, I am still a student and have a lot of schoolwork that I need to focus on. Unfortunately, this means that I will not be able to fully commit to the team at this time. I really love SideStore and wish it all the best for the future. 🥳

**Comment by lonkelle** [comment]
@SoY0ung Oh, don't worry about not committing to anything, there are literal team members of SideStore that are **only there** to have discussions about the future of SideStore and only pop in every couple weeks (even a couple non-devs), so if you even simply want only to have your opinion on the direction of SideStore have more of an impact - we def want ya to join and observe our development (and you don't have to participate at all). You can just hang around until you have a question or opinion and talk away!

Anywayyyy, good luck on all of that schoolwork, me and the the rest of the SideStore team appreciate what you did, and wish you the best of luck in your schooling! ☺️ 

PS. That Discord invite link expires in 7 days.
