### ISSUE TITLE
我用altsever安装这个ipa的时候提示“The app could not be found”怎么办呢

### ISSUE THREAD

**Issue by BlancAlexander** [SoY0ung/SideStore#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please send logs generated with [idevicedebug](https://github.com/libimobiledevice/libimobiledevice) or Xcode. We will close the issue if a log is missing.

**iDevice (please complete the following information):**

**Additional context**

**Comment by SoY0ung** [comment]
是中文的ipa吗？你可以试试把中文ipa改成英文，如果还是不行，可能是SideStore自身的问题，等官方修复。
